[package]
name = "ttt_menace"
version = "1.0.0-alpha.1"
edition = "2021"
readme = "README.md"
repository = "https://github.com/AliSajid/tictactoe"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ttt_menace_lib"
path = "src/ttt_menace/lib.rs"
crate-type = ["lib"]

[[bin]]
name = "tttm"
path = "src/ttt_menace/main.rs"

[dependencies]


[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
incremental = true

[profile.release]
opt-level = 's'
debug = false
debug-assertions = false
strip = "symbols"
overflow-checks = true
lto = true
codegen-units = 1
incremental = false
