# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = [
    ".gitleaksignore",
    ".gitignore",
    ".secrets.baseline",
    ".markdownlintignore",
    ".vscode/*",
    "guide/.gitignore"
]
precedence = "override"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "Cargo.lock"
precedence = "override"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
    "licenses_report.md",
    "licenses_report.json",
    "renovate.json",
    ".markdownlint.json",
    ".vale.ini",
    ".gitpod.yml",
    ".releaserc.yml",
    ".gitpod.Dockerfile"
]
precedence = "override"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/workflows/*"
precedence = "override"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    ".github/ISSUE_TEMPLATE/*",
    ".github/PULL_REQUEST_TEMPLATE.md"
]
precedence = "override"
SPDX-FileCopyrightText = "2022 - 2024 Ali Sajid Imami"
SPDX-License-Identifier = "CC0-1.0"
