# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT
---
name: Security Audit
on:
  schedule:
    - cron: 0 0 1,15 * *
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  workflow_dispatch:
jobs:
  security_audit:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - name: Install cargo-audit
        uses: taiki-e/install-action@25435dc8dd3baed7417e0c96d3fe89013a5b2e09 # v2.81.3
        with:
          tool: cargo-audit
      - name: Security Audit
        run: cargo audit
