# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Code Coverage
on:
    workflow_call:
jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:81639b443dc30490b4fe18bb347f7954e098f05a595a8723f03bf8c58f4b5f14
            options: --security-opt seccomp=unconfined
        steps:
            - name: Checkout repository
              uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
            # Nightly Rust is required for cargo llvm-cov --doc.
            - uses: dtolnay/rust-toolchain@nightly
              with:
                components: llvm-tools-preview
            - uses: taiki-e/install-action@2d57bf37fe9fab88b6ec604bfaa8c76ed00ea64a # v2.44.27
              with:
                tool: cargo-llvm-cov
            - uses: taiki-e/install-action@2d57bf37fe9fab88b6ec604bfaa8c76ed00ea64a # v2.44.27
              with:
                tool: nextest
            - name: Collect coverage data (including doctests)
              run: |
                cargo llvm-cov --no-report nextest --config-file nextest.toml
                cargo llvm-cov --no-report --doc
                cargo llvm-cov report --doctests --lcov --output-path lcov.info
            - name: Upload to codecov.io
              uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
              with:
                file: lcov.info
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
