# SPDX-FileCopyrightText: 2022 - 2024 Ali Sajid Imami
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

---
name: Code Coverage
on:
    workflow_call:
jobs:
    test:
        name: Generate Coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin:develop-nightly@sha256:6883db80eb53ec4cbdc7351696dcc5edeeeaa01add22e78e7c58a8630596f096
            options: --security-opt seccomp=unconfined
        steps:
            - name: Checkout repository
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            # Nightly Rust is required for cargo llvm-cov --doc.
            - uses: dtolnay/rust-toolchain@nightly
              with:
                components: llvm-tools-preview
            - uses: taiki-e/install-action@a209ff0ce0349f9e7cadc4ba8f6a415c8d3b0813 # v2.49.11
              with:
                tool: cargo-llvm-cov
            - uses: taiki-e/install-action@a209ff0ce0349f9e7cadc4ba8f6a415c8d3b0813 # v2.49.11
              with:
                tool: nextest
            - name: Collect coverage data (including doctests)
              run: |
                cargo llvm-cov --no-report nextest --config-file nextest.toml
                cargo llvm-cov --no-report --doc
                cargo llvm-cov report --doctests --lcov --output-path lcov.info
            - name: Upload to codecov.io
              uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
              with:
                file: lcov.info
              env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
